version: '3'
tasks:
  make:
    cmds:
      - nuitka --enable-plugin=tk-inter --follow-imports --standalone --onefile --windows-console-mode=disable --output-dir=build --output-filename=vic src/main.py
