// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsVRChatRunning() {
  return window['go']['main']['App']['IsVRChatRunning']();
}

export function SendChatMessage(arg1) {
  return window['go']['main']['App']['SendChatMessage'](arg1);
}

export function SendTypingStatus(arg1) {
  return window['go']['main']['App']['SendTypingStatus'](arg1);
}
