// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function IsVRChatRunning():Promise<boolean>;

export function SendChatMessage(arg1:string):Promise<main.SendResponse>;

export function SendTypingStatus(arg1:boolean):Promise<main.SendResponse>;
