name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        
    - name: Setup virtual environment
      run: uv venv
        
    - name: Install dependencies
      shell: pwsh
      run: |
        .\.venv\Scripts\Activate.ps1
        uv pip install -e .
        
    - name: Lint with ruff
      shell: pwsh
      run: |
        .\.venv\Scripts\Activate.ps1
        uv pip install ruff
        ruff check .
        
    - name: Build
      shell: pwsh
      run: |
        .\.venv\Scripts\Activate.ps1
        python -m nuitka --enable-plugin=tk-inter --follow-imports --standalone --onefile --output-dir=build --output-filename=vic src/main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vic
        path: build/vic.exe