name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Visual Studio Build Tools
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "vs_buildtools.exe"
        Start-Process -FilePath "vs_buildtools.exe" -ArgumentList "--quiet", "--wait", "--norestart", "--nocache", `
        "--installPath", "C:\BuildTools", `
        "--add", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64", `
        "--add", "Microsoft.VisualStudio.Component.Windows10SDK.19041" `
        -Wait -NoNewWindow
        Remove-Item "vs_buildtools.exe"
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        
    - name: Setup virtual environment
      run: uv venv
        
    - name: Install dependencies
      shell: pwsh
      run: |
        .\.venv\Scripts\Activate.ps1
        uv pip install -e .
        
    - name: Lint with ruff
      shell: pwsh
      run: |
        .\.venv\Scripts\Activate.ps1
        uv pip install ruff
        ruff check .
        
    - name: Build
      shell: pwsh
      run: |
        .\.venv\Scripts\Activate.ps1
        uv run task make
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vic
        path: build/vic.exe