name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Get latest successful VS Build Tools cache
      uses: actions/cache@v3
      id: build-tools-cache
      with:
        path: C:\BuildTools
        key: vs-buildtools-${{ runner.os }}-2022
        restore-keys: |
          vs-buildtools-${{ runner.os }}-

    - name: Check VS Build Tools cache
      if: steps.build-tools-cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Write-Error "VS Build Tools cache not found. Please run the setup-build-tools workflow first."
        exit 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
          uv.lock

    - name: Generate dependency hash
      id: hash
      shell: pwsh
      run: |
        $hash = (Get-FileHash -Path pyproject.toml,uv.lock -Algorithm SHA256 | ForEach-Object {$_.Hash}) -join "-"
        echo "hash=$hash" >> $env:GITHUB_OUTPUT
        
    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        
    - name: Setup virtual environment
      run: uv venv

    - name: Cache virtual environment
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.hash.outputs.hash }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Install dependencies
      shell: pwsh
      run: |
        .\.venv\Scripts\Activate.ps1
        uv pip install -e .

    - name: Cache ruff data
      uses: actions/cache@v3
      with:
        path: C:\Users\runneradmin\AppData\Local\ruff
        key: ruff-${{ runner.os }}-${{ hashFiles('**/*.py') }}
        restore-keys: |
          ruff-${{ runner.os }}-

    - name: Lint
      shell: pwsh
      run: |
        .\.venv\Scripts\Activate.ps1
        uv pip install ruff
        ruff check .

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          target
          build
        key: build-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          build-${{ runner.os }}-
        
    - name: Build application
      shell: pwsh
      run: |
        .\.venv\Scripts\Activate.ps1
        uv run task make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vic
        path: build/vic.exe