name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install rye-tool
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
        rye sync
        
    - name: Lint with ruff
      run: |
        python -m pip install ruff
        ruff check .
        
    - name: Build
      shell: bash
      run: rye run build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vic
        path: build/vic.exe